FROM 811157219101.dkr.ecr.eu-west-2.amazonaws.com/dockerproductionaws/microtrader-base
MAINTAINER Santosh Rai <san_rai@hotmail.com>
LABEL application.component=microtrader-portfolio

# Copy application artefacts
ARG app_version
LABEL application.version=${app_version}
COPY build/jars/microtrader-portfolio-${app_version}-fat.jar /app/app.jar